# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 05:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PayMock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idFirmy', models.IntegerField()),
                ('nazwaFirmy', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Platnosci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('koszt', models.DecimalField(decimal_places=2, max_digits=8)),
                ('nazwaFirmy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PayMock.Firma')),
            ],
        ),
    ]
